[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "https://yesbhautik.co.in/*"
to = "https://yesbhautik.co.in/:splat"
status = 302
force = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
