packages: []
catalogs:
  build:
    '@shikijs/markdown-it': ^3.3.0
    '@shikijs/transformers': ^3.3.0
    '@shikijs/twoslash': ^3.3.0
    '@unocss/preset-web-fonts': ^66.5.2
    '@vitejs/plugin-vue': ^6.0.1
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^0.9.0
    unocss: ^66.5.2
    unplugin-auto-import: ^19.1.3
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.5.0
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.15.0
    vite: ^6.3.0
    vite-plugin-inspect: ^11.1.0
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^28.1.0
    vite-svg-loader: ^5.1.0
  dev:
    '@antfu/eslint-config': ^4.11.1
    '@iconify/json': ^2.2.357
    '@octokit/core': ^6.1.4
    '@octokit/rest': ^21.1.1
    ansis: ^3.17.0
    cross-env: ^7.0.3
    degit: ^2.8.4
    diacritics: ^1.3.0
    eslint: ^9.25.0
    eslint-plugin-format: ^1.0.2
    exifreader: ^4.27.0
    fast-glob: ^3.3.3
    feed: ^4.2.2
    fs-extra: ^11.3.2
    lint-staged: ^15.5.1
    pathe: ^2.0.3
    pnpm: ^10.11.1
    prompts: ^2.4.2
    rimraf: ^6.0.1
    sharp: 0.32.6
    simple-git: ^3.27.0
    simple-git-hooks: ^2.12.1
    tsx: ^4.20.2
    typescript: ~5.9.2
  frontend:
    '@antfu/utils': ^9.2.1
    '@unhead/vue': ^2.0.17
    '@unocss/reset': ^66.5.2
    '@vueuse/core': ^13.1.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    dayjs: ^1.11.10
    floating-vue: ^5.2.2
    matter-attractors: ^0.1.6
    matter-js: ^0.20.0
    nprogress: ^0.2.0
    pinia: ^3.0.3
    pixi.js: ^8.12.2
    shiki: ^3.3.0
    shiki-magic-move: ^1.1.0
    simplex-noise: ^4.0.3
    vue: ^3.5.22
    vue-router: ^4.5.1
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/d3-hierarchy': ^3.1.7
    '@types/d3-shape': ^3.1.7
    '@types/degit': ^2.8.6
    '@types/diacritics': ^1.3.3
    '@types/fs-extra': ^11.0.3
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^22.11.0
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9
onlyBuiltDependencies:
  - esbuild
  - exifreader
  - sharp
  - simple-git-hooks
